name: Pipeline
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: install black
            run: pip install black


    
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: check if black working on code
            run: black blackfile.py 2> /dev/null
          - name: check if code i written without errors
            run: |
                if[$? != 0]; then
                echo "there is aproblem with the code"
    
    
    
