name: Pipeline
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -uses: actions/checkout@v4
            - name: install black
              run: pip install black  
        
    