name: Pipeline
on:
    pull_request:
        branches:
            - main
env:
    GOOGLE_USER: ${{ secrets.USER_NAME }}
    GOOGLE_PASS: ${{ secrets.USER_PASS }}
    



jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: install black
            run: pip install black
          - name: check if black working on code
            run: black --version
          - name: check if code i written without errors
            run: |
                if black blackfile.py; then
                echo "code is good"
                else
                    echo "code is not good"
                fi


    send_email:
            runs-on: ubuntu-latest
            steps:
              - name: Send email notification
                uses: dawidd6/action-send-mail@v3
                with:
                    from: GITHUB
                    server_address: smtp.gmail.com
                    server_port: 587
                    username: ${{ env.GOOGLE_USER }}
                    password: ${{ env.GOOGLE_PASS }}
                    subject: 'Your CI Pipeline'
                    body: |
                        your ci pipeline is acomplished.
                    to: gilgil956111@gmail.com
                    
                    


    
    
    
    
