name: CI Pipline
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: test for echo
            run: echo hello
          - uses: actions/checkout@v4
          - name: ls test
            run: ls
          - name: run the test
            run: python test.py

