name: CI Pipline
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: clone the repo
          - uses: actions/checkout@v4
    
    test:
     runs-on: ubuntu-latest
     steps:
        - name: run the test
          run: python test.py
