name: CI Pipline
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: clone the repo
          - uses: actions/checkout@v4
<<<<<<< HEAD
          - name: run the test
            run: python test.py
=======
    
    test:
     runs-on: ubuntu-latest
     steps:
        - name: run the test
          run: python test.py
>>>>>>> c9540c8b97506a56f033dc1556a3896d9373d9c2
